### ISSUE TITLE
1101错误

### ISSUE THREAD

**Issue by Aballoffox** [kobe-koto/EdgeSub#12]
即使使用自定义域，当订阅链接中包含vless、vmess等关键词后转换出的订阅链接必定报错1101
![image](https://github.com/user-attachments/assets/437a08d4-c764-4e70-ba9c-275286084119)
![image](https://github.com/user-attachments/assets/08c45a16-c7f0-41d2-a0f3-f3e571da6165)
不包含vless，不报错
![image](https://github.com/user-attachments/assets/82a021a8-74c4-4657-be3c-a1de6eddc681)
![image](https://github.com/user-attachments/assets/ca16aaf5-905e-4762-bbde-4364e6c9dd2b)
包含vless，报错

**Comment by kobe-koto** [comment]
请提供最小可复现测试内容.
