### ISSUE TITLE
生成的订阅链接太长了，有没弄短一点的链接？

### ISSUE THREAD

**Issue by kingzengg** [kobe-koto/EdgeSub#14]
生成的订阅链接太长了，有没得弄短一点的链接？

**Comment by kobe-koto** [comment]
下面的 short 功能

**Comment by kingzengg** [comment]
> 下面的 short 功能

short只有一个short ID和short密码，不是url链接，要怎么使用

**Comment by kobe-koto** [comment]
short:xxx 复制到上面，然后再生成链接
