### ISSUE TITLE
请问怎么能固定remote_config

### ISSUE THREAD

**Issue by l455097908** [kobe-koto/EdgeSub#9]
请问怎么能把remote_config，固定为：https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Mini.ini
我在pages项目中设置了remote_config变量不起作用

**Comment by gtang8** [comment]
手动修改fork的仓库里面EdgeSub/src/config/RemoteConfigs.ts，重新部署

**Comment by kobe-koto** [comment]
> 手动修改fork的仓库里面EdgeSub/src/config/RemoteConfigs.ts，重新部署

正确，也可以在 EdgeSub/functions/internal/Converter/ 下的两个文件中修改 BasicConfig.RemoteConfig 字段。

另外使用上的问题应前往 Discussions 进行讨论，故 Close as not planned
